/*
@title: shadow_harvest
@description: "Subterranean light & shadow farming — protect your crystals, grow crops in matching light, harvest before the dark wins."
@author: yourname
@tags: ['strategy', 'puzzle', 'original']
*/

// --- SPRITE KEYS ---
const P  = "p";  // player (farmer)
const W  = "w";  // wall / ground
const CA = "c";  // cyan crystal (active)
const CD = "C";  // cyan crystal (dark)
const MA = "m";  // magenta crystal (active)
const MD = "n";  // magenta crystal (dark)
const AA = "a";  // amber crystal (active)
const AD = "q";  // amber crystal (dark)
const C1 = "1";  // cyan crop (growing)
const C2 = "2";  // cyan crop (mature — harvest with I)
const M1 = "3";  // magenta crop (growing)
const M2 = "4";  // magenta crop (mature)
const A1 = "5";  // amber crop (growing)
const A2 = "6";  // amber crop (mature)
const BA = "b";  // beast (active)
const BS = "B";  // beast (stunned — frozen in box)
const MI = "*";  // mirror (blocks beast path)

// =====================================================
//  LEGEND — 16×16 bitmaps
//  Color chars: . = transparent, 0 = dark, 4 = accent-1, 8 = accent-2
//  Set your actual colors in the editor's color picker
// =====================================================
setLegend(
[ P, bitmap`
................
................
................
................
................
.....444444.....
....44444444....
....44....44....
....44....44....
.....44..44.....
................
................
................
................
................
................`],
[ W, bitmap`
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000
0000000000000000`],
[ CA, bitmap`
................
................
................
.....44444444...
....4444444444..
...444444444444.
...444444444444.
....4444444444..
.....44444444...
......444444....
.......44444....
........4444....
................
................
................
................`],
[ CD, bitmap`
................
................
................
.....00000000...
....0000000000..
...000000000000.
...000000000000.
....0000000000..
.....00000000...
......000000....
.......00000....
........0000....
................
................
................
................`],
[ MA, bitmap`
................
................
................
.....88888888...
....8888888888..
...888888888888.
...888888888888.
....8888888888..
.....88888888...
......888888....
.......88888....
........8888....
................
................
................
................`],
[ MD, bitmap`
................
................
................
.....00000000...
....0000000000..
...000000000000.
...000000000000.
....0000000000..
.....00000000...
......000000....
.......00000....
........0000....
................
................
................
................`],
[ AA, bitmap`
................
................
................
.....44444444...
....4444444444..
...444444444444.
...444444444444.
....4444444444..
.....44444444...
......444444....
.......44444....
........4444....
................
................
................
................`],
[ AD, bitmap`
................
................
................
.....00000000...
....0000000000..
...000000000000.
...000000000000.
....0000000000..
.....00000000...
......000000....
.......00000....
........0000....
................
................
................
................`],
[ C1, bitmap`
................
................
................
................
................
................
.......4........
......4.4.......
.....4..4.......
....4.444.4.....
....4.444.4.....
.....44444......
................
................
................
................`],
[ C2, bitmap`
................
................
................
................
................
................
....4..4..4.....
...4.444.44.....
...4.444.44.....
....4..4..4.....
....4.444.4.....
.....44444......
................
................
................
................`],
[ M1, bitmap`
................
................
................
................
................
................
.......8........
......8.8.......
.....8..8.......
....8.888.8.....
....8.888.8.....
.....88888......
................
................
................
................`],
[ M2, bitmap`
................
................
................
................
................
................
....8..8..8.....
...8.888.88.....
...8.888.88.....
....8..8..8.....
....8.888.8.....
.....88888......
................
................
................
................`],
[ A1, bitmap`
................
................
................
................
................
................
.......4........
......4.4.......
.....4..4.......
....4.444.4.....
....4.444.4.....
.....44444......
................
................
................
................`],
[ A2, bitmap`
................
................
................
................
................
................
....4..4..4.....
...4.444.44.....
...4.444.44.....
....4..4..4.....
....4.444.4.....
.....44444......
................
................
................
................`],
[ BA, bitmap`
................
................
................
................
................
..00.......00...
..0.0.....0.0...
...0.0...0.0....
....0.0.0.0.....
.....00000......
......000.......
................
................
................
................
................`],
[ BS, bitmap`
................
................
................
................
................
..0000000000....
..0........0....
..0........0....
..0........0....
..0........0....
..0000000000....
................
................
................
................
................`],
[ MI, bitmap`
................
................
................
................
................
................
................
8888888888888888
8888888888888888
................
................
................
................
................
................
................`]
);

// =====================================================
//  BACKGROUND & MAPS
//  Beast spawns far from crops — player has breathing room
// =====================================================
setBackground(W);

// Phase 1 — 8×8: beast bottom-right, crop top-left
const level1 = map`
........
..c.....
..1.....
........
...p....
........
......b.
........
`;

// Phase 2 — 10×10: beast bottom-center, crops top-left
const level2 = map`
..........
..c...m...
..........
.1........
..........
.....p....
..........
....3.....
..........
.....b....
`;

// Phase 3 — 10×10: two beasts bottom, amber crystal is the choke point
const level3 = map`
..........
..c...m...
..........
.1........
.....p....
....3.....
......a...
..5.......
..........
..b...b...
`;

setMap(level1);
setSolids([P, W, CA, CD, MA, MD, AA, AD, BA, BS, MI]);
// crops are NOT solid — player walks over them to harvest
setPushables({ [P]: [] });

// =====================================================
//  STATE
// =====================================================
var phase      = 1;
var turn       = 0;
var lightPhase = 0;
var darkTurns  = {c: 0, m: 0, a: 0};
var basket     = {c: 0, m: 0, a: 0};
var beastStun  = 0;
var flashUses  = 1;
var cropTimer  = 0;
var isGameOver = false;
var showMsg    = null;
var showHelp   = true;

// =====================================================
//  HELP SCREEN — shown on load, dismissed by any key
// =====================================================
addText("SHADOW HARVEST", { x: 0, y: 0, color: color`3` });
addText("WASD: move",     { x: 1, y: 2, color: color`3` });
addText("I:harvest J:mirror", { x: 0, y: 4, color: color`3` });
addText("K:flash (stun beast)", { x: 0, y: 6, color: color`3` });
addText("Press any key to start", { x: 0, y: 7, color: color`3` });

// =====================================================
//  INPUT HANDLERS
//  Every handler checks showHelp first — first key dismisses help
// =====================================================
onInput("w", () => {
  if (showHelp) { showHelp = false; clearText(); updateHUD(); return; }
  if (isGameOver) return;
  var p = getFirst(P); if (p) p.y -= 1;
});
onInput("a", () => {
  if (showHelp) { showHelp = false; clearText(); updateHUD(); return; }
  if (isGameOver) return;
  var p = getFirst(P); if (p) p.x -= 1;
});
onInput("s", () => {
  if (showHelp) { showHelp = false; clearText(); updateHUD(); return; }
  if (isGameOver) return;
  var p = getFirst(P); if (p) p.y += 1;
});
onInput("d", () => {
  if (showHelp) { showHelp = false; clearText(); updateHUD(); return; }
  if (isGameOver) return;
  var p = getFirst(P); if (p) p.x += 1;
});

// i = HARVEST — stand on a mature crop
onInput("i", () => {
  if (showHelp || isGameOver) return;
  var p = getFirst(P); if (!p) return;
  var tiles = getTile(p.x, p.y);
  for (var s of tiles) {
    if (s.type === C2) { s.remove(); basket.c++; showMsg = "Lumen " + basket.c + "/3"; }
    if (s.type === M2) { s.remove(); basket.m++; showMsg = "Void "  + basket.m + "/3"; }
    if (s.type === A2) { s.remove(); basket.a++; showMsg = "Ember " + basket.a + "/3"; }
  }
});

// j = PLACE MIRROR — blocks beast path on this tile
onInput("j", () => {
  if (showHelp || isGameOver) return;
  var p = getFirst(P); if (!p) return;
  var tiles = getTile(p.x, p.y);
  for (var s of tiles) { if (s.type === MI) return; }
  addSprite(p.x, p.y, MI);
});

// k = FLASH — stuns all beasts for 3 turns
onInput("k", () => {
  if (showHelp || isGameOver || flashUses <= 0) return;
  flashUses--;
  beastStun = 3;
  var beasts = getAll(BA);
  for (var b of beasts) b.type = BS;
});

onInput("l", () => {
  if (showHelp) { showHelp = false; clearText(); updateHUD(); }
});

// =====================================================
//  AFTER EVERY INPUT — GAME LOGIC
// =====================================================
afterInput(() => {
  if (showHelp) return;
  if (isGameOver) { updateHUD(); return; }

  turn++;
  cropTimer++;

  // Beast stun countdown
  if (beastStun > 0) {
    beastStun--;
    if (beastStun === 0) {
      var stunned = getAll(BS);
      for (var b of stunned) b.type = BA;
    }
  } else {
    moveBeasts();
  }

  // Light phase cycle (every 3 turns)
  if (turn % 3 === 0) lightPhase = (lightPhase + 1) % 3;

  // Crop growth / revert
  growCrops();

  // New crop spawn (every 8 turns)
  if (cropTimer >= 8) { cropTimer = 0; spawnCrop(); }

  // Crystal recovery
  recoverCrystals();

  // Win / lose
  checkWinLose();

  // HUD
  updateHUD();

  // One-frame harvest message
  if (showMsg) {
    addText(showMsg, { x: 0, y: 1, color: color`3` });
    showMsg = null;
  }
});

// =====================================================
//  BEAST AI — moves 1 tile toward nearest active crystal
//  every 2 turns. Can be blocked by mirrors, walls,
//  other beasts. Stunned beasts don't move.
// =====================================================
function moveBeasts() {
  var beasts = getAll(BA);
  for (var b of beasts) {
    var target = getBeastTarget();
    if (!target) continue;

    if (turn % 2 === 0) {
      var dx = target.x - b.x;
      var dy = target.y - b.y;
      var moved = false;

      if (Math.abs(dx) >= Math.abs(dy)) {
        var nx = b.x + (dx > 0 ? 1 : -1);
        if (!beastBlocked(nx, b.y)) { b.x = nx; moved = true; }
        if (!moved) {
          var ny = b.y + (dy > 0 ? 1 : -1);
          if (!beastBlocked(b.x, ny)) b.y = ny;
        }
      } else {
        var ny2 = b.y + (dy > 0 ? 1 : -1);
        if (!beastBlocked(b.x, ny2)) { b.y = ny2; moved = true; }
        if (!moved) {
          var nx2 = b.x + (dx > 0 ? 1 : -1);
          if (!beastBlocked(nx2, b.y)) b.x = nx2;
        }
      }
    }

    // Did beast land on a crystal? Extinguish it.
    var tiles = getTile(b.x, b.y);
    for (var s of tiles) {
      if (s.type === CA) { s.type = CD; darkTurns.c = 3; }
      if (s.type === MA) { s.type = MD; darkTurns.m = 3; }
      if (s.type === AA) { s.type = AD; darkTurns.a = 3; }
    }
  }
}

function getBeastTarget() {
  // Target the nearest active crystal (not dark)
  var c = getFirst(CA); if (c) return c;
  var m = getFirst(MA); if (m) return m;
  var a = getFirst(AA); if (a) return a;
  return null;
}

function beastBlocked(x, y) {
  if (x < 0 || x >= width() || y < 0 || y >= height()) return true;
  var tiles = getTile(x, y);
  for (var s of tiles) {
    if (s.type === MI || s.type === W || s.type === BA || s.type === BS) return true;
  }
  return false;
}

// =====================================================
//  CROP GROWTH — crops mature when lightPhase matches
//  AND the crystal is active. If the crystal is dark
//  during their phase, mature crops REVERT to growing.
// =====================================================
function growCrops() {
  if (lightPhase === 0) {
    if (darkTurns.c === 0) {
      var c = getAll(C1);  for (var s of c)  s.type = C2;
    } else {
      var c2 = getAll(C2); for (var s of c2) s.type = C1;
    }
  }
  if (lightPhase === 1) {
    if (darkTurns.m === 0) {
      var m = getAll(M1);  for (var s of m)  s.type = M2;
    } else {
      var m2 = getAll(M2); for (var s of m2) s.type = M1;
    }
  }
  if (lightPhase === 2) {
    if (darkTurns.a === 0) {
      var a = getAll(A1);  for (var s of a)  s.type = A2;
    } else {
      var a2 = getAll(A2); for (var s of a2) s.type = A1;
    }
  }
}

// =====================================================
//  CROP SPAWN — new crops appear on random empty tiles
//  every 8 turns, keeping the map dynamic
// =====================================================
function spawnCrop() {
  var cropType;
  if (phase === 1)          cropType = C1;
  else if (phase === 2)     cropType = Math.random() > 0.5 ? C1 : M1;
  else                      cropType = [C1, M1, A1][Math.floor(Math.random() * 3)];

  var spots = [];
  for (var y = 0; y < height(); y++) {
    for (var x = 0; x < width(); x++) {
      if (isEmptyTile(x, y)) spots.push({ x: x, y: y });
    }
  }
  if (spots.length > 0) {
    var spot = spots[Math.floor(Math.random() * spots.length)];
    addSprite(spot.x, spot.y, cropType);
  }
}

function isEmptyTile(x, y) {
  var tiles = getTile(x, y);
  for (var s of tiles) {
    if (s.type !== W) return false;
  }
  return true;
}

// =====================================================
//  CRYSTAL RECOVERY — dark crystals come back online
//  after 3 turns
// =====================================================
function recoverCrystals() {
  if (darkTurns.c > 0) {
    darkTurns.c--;
    if (darkTurns.c === 0) {
      var d = getAll(CD); for (var s of d) s.type = CA;
    }
  }
  if (darkTurns.m > 0) {
    darkTurns.m--;
    if (darkTurns.m === 0) {
      var d = getAll(MD); for (var s of d) s.type = MA;
    }
  }
  if (darkTurns.a > 0) {
    darkTurns.a--;
    if (darkTurns.a === 0) {
      var d = getAll(AD); for (var s of d) s.type = AA;
    }
  }
}

// =====================================================
//  WIN / LOSE
// =====================================================
function checkWinLose() {
  if (phase === 1 && basket.c >= 3) { loadPhase(2); return; }
  if (phase === 2 && basket.c >= 3 && basket.m >= 3) { loadPhase(3); return; }
  if (phase === 3 && basket.c >= 3 && basket.m >= 3 && basket.a >= 3) {
    addText("HARVEST COMPLETE", { x: 1, y: 2, color: color`3` });
    addText("The deep lights thrive.", { x: 0, y: 4, color: color`3` });
    isGameOver = true;
    return;
  }
  if (phase === 1 && darkTurns.c >= 5) {
    addText("DARK WON", { x: 2, y: 3, color: color`3` });
    isGameOver = true;
    return;
  }
  if (phase === 3 &&
      darkTurns.c >= 4 && darkTurns.m >= 4 && darkTurns.a >= 4) {
    addText("ALL CRYSTALS DARK", { x: 1, y: 3, color: color`3` });
    isGameOver = true;
  }
}

function loadPhase(nextPhase) {
  phase = nextPhase;
  flashUses = 2;
  beastStun = 0;
  cropTimer = 0;
  darkTurns = {c: 0, m: 0, a: 0};

  clearText();
  if (nextPhase === 2) setMap(level2);
  if (nextPhase === 3) setMap(level3);

  addText("PHASE " + nextPhase, { x: 2, y: 0, color: color`3` });
}

// =====================================================
//  HUD — one line at the top showing game state
//  P = phase, L = light phase (0=cyan 1=magenta 2=amber)
//  c/m/a = harvested crops, F = flashes remaining
// =====================================================
function updateHUD() {
  clearText();
  if (isGameOver) return;
  addText(
    "P" + phase +
    " L:" + lightPhase +
    " c:" + basket.c +
    " m:" + basket.m +
    " a:" + basket.a +
    " F:" + flashUses,
    { x: 0, y: 0, color: color`3` }
  );
}
